const fs = require('fs');
let c = fs.readFileSync('src/services/reporting.js', 'utf8');

c = c.replace(/    \} else \{\s*\/\/\s*Guard-wise Logic \(Summary \+ Table\)/, "    } else if (type === 'All-Guards-Payout') {\n        const totalPayout = data.reduce((acc, curr) => acc + (Number(curr.payout) || 0), 0);\n        \n        const summaryBlock = `\n            <div class=\"summary-box\">\n                <div class=\"summary-row\"><span class=\"summary-label\">Month:</span><span class=\"summary-value\">${month}</span></div>\n                <div class=\"summary-row\"><span class=\"summary-label\">Total Guards:</span><span class=\"summary-value\">${data.length}</span></div>\n                <div class=\"summary-row total-row\"><span class=\"summary-label\">Final Amount:</span><span class=\"summary-value total-value\">₹${totalPayout}</span></div>\n            </div>\n        `;\n\n        const rows = data.map(item => `\n            <tr>\n                <td>${item.guardName}</td>\n                <td style=\"text-align: center;\">${item.duties}</td>\n                <td style=\"text-align: right; color: #dc3545;\">${item.advanced}</td>\n                <td style=\"text-align: right; font-weight: bold;\">${item.payout}</td>\n            </tr>\n        `).join('');\n\n        content = `\n            ${summaryBlock}\n            <h3>Payout Details</h3>\n            <table>\n                <thead>\n                    <tr>\n                        <th>Guard Name</th>\n                        <th style=\"text-align: center;\">Duties</th>\n                        <th style=\"text-align: right;\">Advanced</th>\n                        <th style=\"text-align: right;\">Payout</th>\n                    </tr>\n                </thead>\n                <tbody>\n                    ${rows}\n                </tbody>\n            </table>\n        `;\n    } else {\n        // Guard-wise Logic (Summary + Table)");

c = c.replace(/    \} else \{\s*\/\/\s*Guard-wise\s*\/\/\s*Summary Block/, "    } else if (type === 'All-Guards-Payout') {\n        const totalPayout = data.reduce((acc, curr) => acc + (Number(curr.payout) || 0), 0);\n        \n        wsData.push(['PAYOUT STATEMENT']);\n        wsData.push(['Month', month]);\n        wsData.push(['Total Guards', data.length]);\n        wsData.push(['Final Amount', totalPayout]);\n        wsData.push([]);\n\n        wsData.push(['Guard Name', 'Duties', 'Advanced', 'Payout']);\n\n        data.forEach(item => {\n            wsData.push([item.guardName, item.duties, item.advanced, item.payout]);\n        });\n    } else {\n        // Guard-wise\n        // Summary Block");

fs.writeFileSync('src/services/reporting.js', c, 'utf8');
console.log("Updated reporting.js");
