import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import XLSX from 'xlsx';
import { formatDate } from '../utils/date';

// Re-using the same parser logic from the UI so exports exactly match the screen
export const parseLegacyExportShift = (item) => {
    if (item.shiftType) {
        return item.shiftType === 'Day' ? 'Day Shift' : 'Night Shift';
    }
    if (!item.startTime || !item.endTime || item.startTime === '-' || item.endTime === '-') {
        return '-';
    }
    const startHour = parseInt(item.startTime.split(':')[0], 10);
    if (startHour >= 8 && startHour < 20) {
        return 'Day Shift';
    } else {
        return 'Night Shift';
    }
};

// HTML Template for PDF
const createHTML = (title, subtitle, content) => `
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; }
        h1 { color: #1111d4; text-align: center; margin-bottom: 5px; }
        h2 { color: #666; text-align: center; margin-top: 0; margin-bottom: 20px; font-weight: normal; font-size: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
        th { background-color: #f2f2f2; color: #333; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .summary-box { background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #eee; }
        .summary-row { display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 14px; }
        .summary-label { color: #666; }
        .summary-value { font-weight: bold; color: #333; }
        .total-row { border-top: 1px solid #ddd; padding-top: 8px; margin-top: 8px; font-size: 16px; }
        .total-value { color: #28a745; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <h1>${title}</h1>
    <h2>${subtitle}</h2>
    ${content}
    <div class="footer">Generated by GuardManager App</div>
</body>
</html>
`;

export const sharePDF = async (type, entityName, month, data) => {
    let content = '';

    if (type === 'Site-wise') {
        const dutiesCount = data.length;
        const guardMap = {};
        const groupedByDate = {};

        data.forEach(item => {
            guardMap[item.guardName] = (guardMap[item.guardName] || 0) + 1;
            if (!groupedByDate[item.date]) groupedByDate[item.date] = [];
            groupedByDate[item.date].push(item);
        });

        const sortedDates = Object.keys(groupedByDate).sort();
        const totalGuards = Object.keys(guardMap).length;

        const summaryRows = Object.entries(guardMap).map(([name, count]) => `
            <div style="margin-left: 20px; font-size: 13px; color: #555;">${name} - ${count} duties</div>
        `).join('');

        const summaryBlock = `
            <div class="summary-box" style="padding-bottom: 25px;">
                <div style="font-size: 16px; font-weight: bold; margin-bottom: 12px; color: #1111d4;">Site Name - ${entityName}</div>
                <div class="summary-row"><span class="summary-label">Total duties done -</span><span class="summary-value">${dutiesCount}</span></div>
                <div class="summary-row" style="margin-bottom: 8px;"><span class="summary-label">Total Guard worked -</span><span class="summary-value">${totalGuards}</span></div>
                ${summaryRows}
            </div>
        `;

        const groupedTables = sortedDates.map(date => {
            const records = groupedByDate[date].sort((a, b) => a.guardName.localeCompare(b.guardName));

            const TRs = records.map(item => {
                const shiftFormat = parseLegacyExportShift(item);

                return `
                <tr>
                    <td style="width: 50%;">${item.guardName}</td>
                    <td style="width: 50%; color: #555;">${shiftFormat}</td>
                </tr>
                `;
            }).join('');

            return `
                <div style="margin-top: 20px; font-weight: bold; font-size: 14px; background: #f2f2f2; padding: 8px; border: 1px solid #ddd; border-bottom: none;">
                    ${formatDate(date)} -
                </div>
                <table style="margin-top: 0;">
                    <tbody>
                        ${TRs}
                    </tbody>
                </table>
            `;
        }).join('');

        content = `
            ${summaryBlock}
            <h3>Grouped by Date</h3>
            ${groupedTables}
        `;
    } else if (type === 'Daily') {
        const groupedBySite = {};

        data.forEach(item => {
            if (!groupedBySite[item.siteName]) groupedBySite[item.siteName] = [];
            groupedBySite[item.siteName].push(item);
        });

        const sortedSites = Object.keys(groupedBySite).sort();

        const groupedTables = sortedSites.map(siteName => {
            const records = groupedBySite[siteName].sort((a, b) => a.guardName.localeCompare(b.guardName));

            const TRs = records.map(item => {
                return `
                <tr>
                    <td style="width: 50%; padding-left: 20px;">${item.guardName}</td>
                    <td style="width: 50%; color: #555;">${parseLegacyExportShift(item)}</td>
                </tr>
                `;
            }).join('');

            return `
                <div style="margin-top: 20px; font-weight: bold; font-size: 15px; color: #1111d4; padding: 4px;">
                    Site Name - ${siteName}
                </div>
                <table style="margin-top: 5px;">
                    <thead>
                        <tr>
                            <th style="padding-left: 10px;">Guards -</th>
                            <th>Shift</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${TRs}
                    </tbody>
                </table>
            `;
        }).join('');

        content = `
            <div style="font-size: 16px; font-weight: bold; margin-bottom: 20px; background: #f2f2f2; padding: 12px; border-radius: 4px;">
                Date - ${month}
            </div>
            ${groupedTables}
        `;
    } else {
        // Guard-wise Logic (Summary + Table)
        if (!data || !data.attendance) return;

        const summary = `
            <div class="summary-box">
                <div class="summary-row"><span class="summary-label">Month:</span><span class="summary-value">${data.month}</span></div>
                <div class="summary-row"><span class="summary-label">Days Worked:</span><span class="summary-value">${data.daysWorked}</span></div>
                <div class="summary-row"><span class="summary-label">Monthly Salary:</span><span class="summary-value">₹${data.monthlySalary}</span></div>
                <div class="summary-row"><span class="summary-label">Total Advances:</span><span class="summary-value" style="color: #dc3545;">- ₹${data.totalAdvances}</span></div>
                <div class="summary-row total-row"><span class="summary-label">Final Payable:</span><span class="summary-value total-value">₹${data.finalPayable}</span></div>
            </div>
        `;

        const rows = data.attendance.map(item => `
            <tr>
                <td>${formatDate(item.date)}</td>
                <td>${item.siteName}</td>
                <td colspan="2" style="text-align: center;">${parseLegacyExportShift(item)}</td>
            </tr>
        `).join('');

        content = `
            ${summary}
            <h3>Attendance History</h3>
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Site Name</th>
                        <th colspan="2" style="text-align: center;">Shift</th>
                    </tr>
                </thead>
                <tbody>
                    ${rows}
                </tbody>
            </table>
        `;
    }

    const html = createHTML(`${type} Report`, `${entityName} - ${month}`, content);

    try {
        const { uri } = await Print.printToFileAsync({ html });
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('Error generating PDF:', error);
        throw error;
    }
};

export const shareExcel = async (type, entityName, month, data) => {
    let wsData = [];

    if (type === 'Site-wise') {
        const dutiesCount = data.length;
        const guardMap = {};
        const groupedByDate = {};

        data.forEach(item => {
            guardMap[item.guardName] = (guardMap[item.guardName] || 0) + 1;
            if (!groupedByDate[item.date]) groupedByDate[item.date] = [];
            groupedByDate[item.date].push(item);
        });

        const sortedDates = Object.keys(groupedByDate).sort();
        const totalGuards = Object.keys(guardMap).length;

        wsData.push(['Site Name', entityName]);
        wsData.push(['Total duties done', dutiesCount]);
        wsData.push(['Total Guard worked', totalGuards]);

        Object.entries(guardMap).forEach(([name, count]) => {
            wsData.push(['', `${name} - ${count} duties`]);
        });

        wsData.push([]);

        // Grouped by date body
        sortedDates.forEach(date => {
            wsData.push([`${formatDate(date)} -`]); // Date Header Row
            const records = groupedByDate[date].sort((a, b) => a.guardName.localeCompare(b.guardName));

            records.forEach(item => {
                const shiftFormat = parseLegacyExportShift(item);

                wsData.push([item.guardName, shiftFormat]);
            });
            wsData.push([]); // Gap between dates
        });
    } else if (type === 'Daily') {
        const groupedBySite = {};

        data.forEach(item => {
            if (!groupedBySite[item.siteName]) groupedBySite[item.siteName] = [];
            groupedBySite[item.siteName].push(item);
        });

        const sortedSites = Object.keys(groupedBySite).sort();

        // 1. Top Level Date Header
        wsData.push([`Date - ${month}`]);
        wsData.push([]);

        // 2. Loop over Sites
        sortedSites.forEach(siteName => {
            wsData.push([`Site Name - ${siteName}`]);
            wsData.push(['Guards -', 'Shift']); // Column Headers for this Sub-table

            const records = groupedBySite[siteName].sort((a, b) => a.guardName.localeCompare(b.guardName));
            records.forEach(item => {
                wsData.push([item.guardName, parseLegacyExportShift(item)]);
            });

            wsData.push([]); // blank row spacing
        });
    } else {
        // Guard-wise
        // Summary Block
        wsData.push(['SALARY STATEMENT']);
        wsData.push(['Month', data.month]);
        wsData.push(['Guard Name', entityName]);
        wsData.push(['Days Worked', data.daysWorked]);
        wsData.push(['Monthly Salary', data.monthlySalary]);
        wsData.push(['Total Advances', data.totalAdvances]);
        wsData.push(['Final Payable', data.finalPayable]);
        wsData.push([]); // Empty row

        // Table Headers
        wsData.push(['ATTENDANCE HISTORY']);
        wsData.push(['Date', 'Site Name', 'Shift']);

        // Data
        if (data.attendance) {
            data.attendance.forEach(item => {
                wsData.push([formatDate(item.date), item.siteName, parseLegacyExportShift(item)]);
            });
        }
    }

    try {
        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.aoa_to_sheet(wsData);
        XLSX.utils.book_append_sheet(wb, ws, "Report");

        const wbout = XLSX.write(wb, { type: 'base64', bookType: 'xlsx' });
        const fileName = `Report_${type.replace(' ', '_')}_${month}.xlsx`;
        const uri = FileSystem.cacheDirectory + fileName;

        await FileSystem.writeAsStringAsync(uri, wbout, { encoding: 'base64' });
        await Sharing.shareAsync(uri, { UTI: '.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
        return uri;
    } catch (error) {
        console.error('Error generating Excel:', error);
        throw error;
    }
};

/**
 * Generate and share a PDF for Advances
 */
export const shareAdvancesPDF = async (advancesList, totalAmount, monthStr) => {
    try {
        const rows = advancesList.map(item => `
            <tr>
                <td>${item.guardName || 'Unknown'}</td>
                <td>${item.date}</td>
                <td style="text-align: right; color: #d9534f; font-weight: bold;">-₹${Number(item.amount).toFixed(2)}</td>
            </tr>
        `).join('');

        const [year, month] = monthStr.split('-');
        const dateObj = new Date(year, month - 1);
        const displayMonth = dateObj.toLocaleString('default', { month: 'long', year: 'numeric' });

        const htmlRaw = `
            <!DOCTYPE html>
            <html>
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
                    <style>
                        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #272727; }
                        h1 { color: #4F98CA; text-align: center; margin-bottom: 5px; }
                        .summary-box { 
                            background-color: #EFFFFB; 
                            border: 2px solid #50D890; 
                            border-radius: 8px; 
                            padding: 15px; 
                            margin: 20px 0; 
                            text-align: center;
                        }
                        .summary-title { font-size: 16px; color: #4F98CA; margin-bottom: 5px; font-weight: bold; }
                        .summary-amount { font-size: 24px; color: #272727; font-weight: bold; }
                        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                        th { background-color: #4F98CA; color: white; padding: 12px; text-align: left; }
                        th:last-child { text-align: right; }
                        td { padding: 12px; border-bottom: 1px solid #eee; }
                        tr:nth-child(even) { background-color: #f9f9f9; }
                    </style>
                </head>
                <body>
                    <h1>Advances Report</h1>
                    <p style="text-align: center; color: #666; margin-top: 0;">Generated on ${new Date().toLocaleDateString()}</p>

                    <div class="summary-box">
                        <div class="summary-title">Total Advances for ${displayMonth}</div>
                        <div class="summary-amount">₹${totalAmount.toFixed(2)}</div>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th>Guard Name</th>
                                <th>Date Issued</th>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${rows}
                        </tbody>
                    </table>
                </body>
            </html>
        `;

        const { uri } = await Print.printToFileAsync({ html: htmlRaw });

        if (await Sharing.isAvailableAsync()) {
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } else {
            alert('Sharing is not available on this device');
        }

        return uri;
    } catch (error) {
        console.error('Error generating Advances PDF:', error);
        throw error;
    }
};
