import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import XLSX from 'xlsx';
import { formatDate } from '../utils/date';

// HTML Template for PDF
const createHTML = (title, subtitle, content) => `
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; }
        h1 { color: #1111d4; text-align: center; margin-bottom: 5px; }
        h2 { color: #666; text-align: center; margin-top: 0; margin-bottom: 20px; font-weight: normal; font-size: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
        th { background-color: #f2f2f2; color: #333; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .summary-box { background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #eee; }
        .summary-row { display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 14px; }
        .summary-label { color: #666; }
        .summary-value { font-weight: bold; color: #333; }
        .total-row { border-top: 1px solid #ddd; padding-top: 8px; margin-top: 8px; font-size: 16px; }
        .total-value { color: #28a745; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <h1>${title}</h1>
    <h2>${subtitle}</h2>
    ${content}
    <div class="footer">Generated by GuardManager App</div>
</body>
</html>
`;

export const sharePDF = async (type, entityName, month, data) => {
    let content = '';

    if (type === 'Site-wise') {
        const rows = data.map(item => `
            <tr>
                <td>${formatDate(item.date)}</td>
                <td>${item.guardName}</td>
                <td>${item.startTime}</td>
                <td>${item.endTime}</td>
            </tr>
        `).join('');

        content = `
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Guard Name</th>
                        <th>Time In</th>
                        <th>Time Out</th>
                    </tr>
                </thead>
                <tbody>
                    ${rows}
                </tbody>
            </table>
        `;
    } else {
        // Guard-wise Logic (Summary + Table)
        if (!data || !data.attendance) return;

        const summary = `
            <div class="summary-box">
                <div class="summary-row"><span class="summary-label">Month:</span><span class="summary-value">${data.month}</span></div>
                <div class="summary-row"><span class="summary-label">Days Worked:</span><span class="summary-value">${data.daysWorked}</span></div>
                <div class="summary-row"><span class="summary-label">Monthly Salary:</span><span class="summary-value">₹${data.monthlySalary}</span></div>
                <div class="summary-row"><span class="summary-label">Total Advances:</span><span class="summary-value" style="color: #dc3545;">- ₹${data.totalAdvances}</span></div>
                <div class="summary-row total-row"><span class="summary-label">Final Payable:</span><span class="summary-value total-value">₹${data.finalPayable}</span></div>
            </div>
        `;

        const rows = data.attendance.map(item => `
            <tr>
                <td>${formatDate(item.date)}</td>
                <td>${item.siteName}</td>
                <td>${item.startTime}</td>
                <td>${item.endTime}</td>
            </tr>
        `).join('');

        content = `
            ${summary}
            <h3>Attendance History</h3>
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Site Name</th>
                        <th>Time In</th>
                        <th>Time Out</th>
                    </tr>
                </thead>
                <tbody>
                    ${rows}
                </tbody>
            </table>
        `;
    }

    const html = createHTML(`${type} Report`, `${entityName} - ${month}`, content);

    try {
        const { uri } = await Print.printToFileAsync({ html });
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('Error generating PDF:', error);
        throw error;
    }
};

export const shareExcel = async (type, entityName, month, data) => {
    let wsData = [];

    if (type === 'Site-wise') {
        // Headers
        wsData.push(['Date', 'Guard Name', 'Time In', 'Time Out']);
        // Data
        data.forEach(item => {
            wsData.push([formatDate(item.date), item.guardName, item.startTime, item.endTime]);
        });
    } else {
        // Guard-wise
        // Summary Block
        wsData.push(['SALARY STATEMENT']);
        wsData.push(['Month', data.month]);
        wsData.push(['Guard Name', entityName]);
        wsData.push(['Days Worked', data.daysWorked]);
        wsData.push(['Monthly Salary', data.monthlySalary]);
        wsData.push(['Total Advances', data.totalAdvances]);
        wsData.push(['Final Payable', data.finalPayable]);
        wsData.push([]); // Empty row

        // Table Headers
        wsData.push(['ATTENDANCE HISTORY']);
        wsData.push(['Date', 'Site Name', 'Time In', 'Time Out']);

        // Data
        if (data.attendance) {
            data.attendance.forEach(item => {
                wsData.push([formatDate(item.date), item.siteName, item.startTime, item.endTime]);
            });
        }
    }

    try {
        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.aoa_to_sheet(wsData);
        XLSX.utils.book_append_sheet(wb, ws, "Report");

        const wbout = XLSX.write(wb, { type: 'base64', bookType: 'xlsx' });
        const fileName = `Report_${type.replace(' ', '_')}_${month}.xlsx`;
        const uri = FileSystem.cacheDirectory + fileName;

        await FileSystem.writeAsStringAsync(uri, wbout, { encoding: 'base64' });
        await Sharing.shareAsync(uri, { UTI: '.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    } catch (error) {
        console.error('Error generating Excel:', error);
        throw error;
    }
};
